PrinterFac/Eprint_admin/urls.py
from django.conf.urls import url
from django.urls import path
from . import views
urlpatterns = [
    path('', views.tasks, name='admin-tasks'),
    path('<str:order_by>', views.tasks, name='admin-tasks'),
    path('update/', views.update_prices, name='admin-update')
]


PrinterFac/PrinterFac/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('baseApp.urls')),
    path('users/', include('Eprint_users.urls')),
    path('EAdmin/', include('Eprint_admin.urls')),
]

PrinterFac/baseApp/urls.py
from django.conf.urls import url
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

# Path is basically the URL, the view logic file and name of URL
# History is like profile

urlpatterns = [
    path('home', views.home, name='baseApp-home'),
    path('about/', views.about, name='baseApp-about'),
    path('', views.login, name='login'),
    path('login/', auth_views.LoginView.as_view(template_name='ground/login.html'), name='loginPage'),
    path('logout/', auth_views.LogoutView.as_view(template_name='ground/logout.html'), name='logout'),

    path('password_reset/',
         auth_views.PasswordResetView.as_view(template_name='ground/password_reset/password_reset_form.html'),
         name='password_reset'),
    path('password_reset/done/',
         auth_views.PasswordResetDoneView.as_view(template_name='ground/password_reset/password_reset_done.html'),
         name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        auth_views.PasswordResetConfirmView.as_view(template_name='ground/password_reset/password_reset_confirm.html'),
        name='password_reset_confirm'),
    path(r'password_reset/complete/',
         auth_views.PasswordResetCompleteView.as_view(template_name='ground/password_reset/password_reset_complete.html'),
         name='password_reset_complete'),
]

PrinterFac/Eprint_admin/models.py
from django.db import models


class RatePerPage(models.Model):
    rppBW = models.FloatField(default=3)
    rppC = models.FloatField(default=5)

PrinterFac/Eprint_users/models.py
import uuid

from django.conf import settings
from django.db import models
from django.contrib.auth.models import User
from django.contrib.auth import get_user_model
from django.db.models.signals import post_save
from django.dispatch import receiver


def get_sentinel_user():  # Sets a user to deleted when a task of a delete user is requested
    return get_user_model().objects.get_or_create(username='deleted')[0]


# sqlmigrate app 000x for SQL code of migrate

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    aadhar_verified = models.BooleanField(default=False)
    license_verified = models.BooleanField(default=False)
    license_num = models.CharField(default='', max_length=15)
    aadhar_num = models.CharField(default='', max_length=12)
    wallet = models.DecimalField(max_digits=6, decimal_places=2, default=100.00)
    rating = models.DecimalField(max_digits=3, decimal_places=2, default=3.00)

    def __str__(self):
        return f'{self.user.username} Profile'


@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)


@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()


class HostSearch(models.Model):
    source_point = models.CharField(max_length=25, default='')
    dest_point = models.CharField(max_length=25, default='')
    AC = models.BooleanField(default=False)
    seats_vac = models.IntegerField(default=1)
    start_time = models.DateTimeField(auto_now_add=True, editable=False)
    task_by = models.ForeignKey(User, on_delete=models.CASCADE, default=None)
    completed = models.BooleanField(default=False)
    charge = models.DecimalField(max_digits=4, decimal_places=2, default=30.00)
    rating1= models.DecimalField(max_digits=3, decimal_places=2, default=3.00)
    rating2 = models.DecimalField(max_digits=3, decimal_places=2, default=3.00)

    class Meta:
        verbose_name = 'HostSearch'  # Name of registered model in Admin panel

class PrintDocs(models.Model):
    description = models.CharField(max_length=255, default='')
    document = models.FileField(upload_to=settings.EASY_PRINT_MEDIA_DIR)
    file_name = models.CharField(max_length=500, default='no_name_given')
    date_uploaded = models.DateTimeField(auto_now_add=True)
    colour = models.BooleanField(default=False)  # 0 for black
    copies = models.SmallIntegerField(default=1)
    task_by = models.ForeignKey(User, on_delete=models.SET(get_sentinel_user))
    num_pages = models.SmallIntegerField(default=1)
    price = models.DecimalField(default=0, max_digits=10, decimal_places=2)
    completed = models.BooleanField(default=False)
    paid = models.BooleanField(default=False)
    collected = models.BooleanField(default=False)
    is_confirmed = models.BooleanField(default=False)
    order_id = models.CharField(max_length=50, default='')

    # def __str__(self):
    #     return self.document.name

    class Meta:
        verbose_name = 'Document'  # Name of registered model in Admin panel


class CustSearch(models.Model):
    pickup_loc = models.CharField(max_length=25, default='')
    drop_loc = models.CharField(max_length=25, default='')
    AC_pref = models.BooleanField(default=False)
    seats_req = models.IntegerField(default=1)
    start_time = models.DateTimeField(auto_now_add=True, editable=False)
    request_to = models.ForeignKey(HostSearch, on_delete=models.CASCADE, default=None, null=True)
    host_accept = models.BooleanField(default=False)
    completed = models.BooleanField(default=False)
    task_by = models.ForeignKey(User, on_delete=models.CASCADE, default=None)
    charge = models.DecimalField(max_digits=4, decimal_places=2, default=30.00)
    rating = models.DecimalField(max_digits=3, decimal_places=2, default=3.00)

    # def __str__(self):  # How to Display a CustSearch object
    #     return self.document.name

    class Meta:
        verbose_name = 'CustSearch'  # Name of registered model in Admin panel

PrinterFac/Eprint_admin/forms.py
from django import forms
from Eprint_users.models import PrintDocs
from . models import RatePerPage


class UpdateForm(forms.ModelForm):
    class Meta:
        model = PrintDocs
        fields = ['task_by', 'completed', 'paid', 'collected', 'id']


class ChangeRate(forms.ModelForm):
    class Meta:
        model = RatePerPage
        fields = ['rppBW']

    def __init__(self, *args, **kwargs):
        super(ChangeRate, self).__init__(*args, **kwargs)
        self.fields['rppBW'].label = "Black and White"
        # self.fields['rppC'].label = "Colour"
        self.fields['rppBW'].help_text = "Per Page (One Side)"
        # self.fields['rppC'].help_text = "Per Page (One Side)"

PrinterFac/Eprint_admin/views.py
import os
import subprocess

from django.conf import settings
from django.contrib import messages
from django.db.models import Q
from django.shortcuts import render, redirect
from Eprint_admin.models import RatePerPage
from Eprint_users.models import PrintDocs, Profile
from .forms import UpdateForm, ChangeRate
from django.contrib.admin.views.decorators import user_passes_test


@user_passes_test(lambda u: u.is_staff, login_url='login')  # Decorator for staff access
def tasks(request):
    # Get filter
    query = None
    filter_by = request.GET.get('filter_by') or 'all'

    # Updating jobs
    run_queue = subprocess.run(["lpq"], encoding='utf-8', stdout=subprocess.PIPE)
    output = run_queue.stdout

    s = [line.split() for line in output.split('\n')]
    s = s[2:]
    pending = [int(row[3]) for row in s if len(row) >= 4]
    printed_docs = PrintDocs.objects.filter(completed=False).exclude(id__in=pending)
    printed_docs.update(completed=True)

    # If query exists in get variables
    if request.GET.get('query'):
        query = request.GET.get('query')
        docs = PrintDocs.objects.filter(Q(file_name__icontains=query) | Q(task_by__username__icontains=query),
                                        is_confirmed=True)
        # Q objects are a way to OR queries together
    else:
        docs = PrintDocs.objects.filter(is_confirmed=True)
    
    # Filter_by_here
    docs = docs.order_by("-date_uploaded")
    if filter_by == 'paid':
        docs = docs.filter(paid="True")
    elif filter_by == 'collected':
        docs = docs.filter(collected="True")
    elif filter_by == "completed":
        docs = docs.filter(completed="True")

    forms = []  # List for all the forms to be shown
    edits = {x: False for x in range(len(docs))}  # Count the number of edits for confirmation message

    if request.method == 'POST':
        i = -1
        for doc in docs:
            i += 1
            temp_doc = PrintDocs.objects.filter(id=doc.id).first()

            '''
            Here is the core of admin tasks.
            Using model formsets was the legit way to do this, but styling it was hard since crispy forms are being
            used.
            Hence, a simple hard-coded way to achieve the desired outcome.
            
            All the form elements in the rendered template are given an ID, which is collected here and used to update
            documents one by one.
            '''

            if request.POST.get('completed' + str(i)) is None:
                if temp_doc.completed is True:
                    temp_doc.completed = False
                    edits[i] = True
            elif request.POST.get('completed' + str(i)) == 'on':
                if temp_doc.completed is False:
                    temp_doc.completed = True
                    edits[i] = True

            if request.POST.get('paid' + str(i)) is None:
                if temp_doc.paid is True:
                    temp_doc.paid = False
                    edits[i] = True
            elif request.POST.get('paid' + str(i)) == 'on':
                if temp_doc.paid is False:
                    temp_doc.paid = True
                    edits[i] = True

                    # Adding amount due to profile
                    temp_pro = Profile.objects.filter(id=temp_doc.task_by.profile.id).first()
                    temp_pro.amount_due -= temp_doc.price
                    temp_pro.save()

            if request.POST.get('collected' + str(i)) is None:
                if temp_doc.collected is True:
                    temp_doc.collected = False
                    edits[i] = True
            elif request.POST.get('collected' + str(i)) == 'on':
                if temp_doc.collected is False:
                    temp_doc.collected = True
                    edits[i] = True
            temp_doc.save()

        # Reprinting
        reprints = PrintDocs.objects.filter(is_confirmed=True)
        for reprint in reprints:
            if request.POST.get('reprint' + str(reprint.id)) == 'on':
                cmd = "lp"
                args = ["-U " + str(reprint.task_by_id)]
                args += ["-n " + str(reprint.copies)]
                args += ["-t " + str(reprint.id)]
                args += [reprint.document.name]
                # args += ["-d " + settings.EASY_PRINT_PRINTER_NAME]  # Not working for now
                subprocess.run([cmd, *args], encoding='utf-8', stdout=subprocess.PIPE)

        if sum(edits.values()) > 0:
            messages.success(request, 'Successfully updated {0} document(s)'.format(sum(edits.values())))
        return redirect('admin-tasks')
    else:
        for doc in docs:
            temp_form = UpdateForm(instance=doc)
            forms.append(temp_form)

        ids = [i for i in range(len(forms))]
        ground_file_names = [os.path.basename(i.document.name) for i in docs]
        context = zip(docs, forms, ids, ground_file_names)
        # curr_dir = os.getcwd().replace('\\', '/'), 'curr_dir': curr_dir,
        return render(request, 'Eprint_admin/tasks.html',
                      {'context': context, 'host': settings.EASY_PRINT_MEDIA_HOST,
                       'media_dir': settings.EASY_PRINT_MEDIA_DIR, 'filter_by': filter_by, 'query': query})


@user_passes_test(lambda u: u.is_staff, login_url='login')
def update_prices(request):

    if request.method == 'POST':
        form = ChangeRate(request.POST, instance=RatePerPage.objects.first())
        if form.is_valid():
            form.save()
            messages.success(request, 'Successfully updated prices')
            return redirect('admin-update')
    else:
        form = ChangeRate(instance=RatePerPage.objects.first())
        return render(request, 'Eprint_admin/update.html', {'update_form': form})

PrinterFac/Eprint_admin/templates/Eprint_admin/tasks.html
{% extends "ground/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="content-below-nav">
        {% if messages %}
            {% for message in messages %}
                <center>
                    <ul style="list-style: none; padding: 0; margin: 0;">
                        <li class="alert alert-{{ message.tags }} alert-dismissible">
                            <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                            {{ message }}
                        </li>
                    </ul>
                </center>
            {% endfor %}
        {% endif %}
        <center>
            <div class="table-responsive">
                <table class="table-borderless">
                    <tr>
                        <td colspan="4"></td>
                    </tr>
                </table>
            </div>
            <br>
            <h1>Tasks</h1><br><br>
            <div style="padding-bottom: 3%;">
                <form method="get" class="form active-cyan-4">
                    <input id="query" name="query" style="width: 80%; border-radius: 40px; margin-bottom: 1%;"
                           class="form-control form-control-sm" type="text"
                           placeholder="Search in documents or users" aria-label="Search">
                    <button class="small-btn btn aqua-gradient shadow-none"><strong>Search</strong></button>
                </form>
            </div>
            <form method="post" enctype="multipart/form-data">
                <ul class="nav nav-tabs bill-table">
                    <li class="nav-item">
                        <a class="nav-link {% if filter_by == "all" %}active {% else %} text-white {% endif %}"
                           href="/EAdmin/{% if query is not None %}?query={{ query }}{% endif %}"> All </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link {% if filter_by == "completed" %}active {% else %} text-white {% endif %}"
                           href="/EAdmin/?filter_by=completed&{% if query is not None %}query={{ query }}{% endif %} ">
                            Completed </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link {% if filter_by == "collected" %}active {% else %} text-white {% endif %}"
                           href="/EAdmin/?filter_by=collected&{% if query is not None %}query={{ query }}{% endif %} ">
                            Collected </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link {% if filter_by == "paid" %}active {% else %} text-white {% endif %}"
                           href="/EAdmin/?filter_by=paid&{% if query is not None %}query={{ query }}{% endif %} ">
                            Paid </a>
                    </li>
                    <li class="nav-item ml-auto">
                        <button class="small-btn btn btn-danger shadow-none"><strong>Update</strong></button>
                    </li>
                </ul>
                {% csrf_token %}
                <div class="table-responsive">
                    <table class="bill-table table-borderless">
                        <tr>
                            <th>Document</th>
                            <th>User</th>
                            <th>Status</th>
                            <th>Action</th>
                        </tr>
                        {% for mytask in context %}
                            <tr>
                                <td class="deep-blue-gradient"><strong>{{ mytask.0.file_name }}</strong><br>
                                    <span class="small text-muted">{{ mytask.0.date_uploaded }}</span>
                                </td>
                                <td>{{ mytask.0.task_by.email }}</td>
                                <td>
                                    <table class="mx-auto">
                                        {% for element in mytask.1 %}
                                            {% if forloop.counter != 1 %}
                                                <tr>
                                                    <td class="text-right" style="background: none;">{{ element.label }}:</td>
                                                    <td style="background: none;">&nbsp;
                                                        <input type="checkbox" style="width: 16px;height: 16px;"
                                                               name="{{ element.name }}{{ mytask.2 }}"
                                                               id="id_completed"
                                                               {% if element.value == True %}checked{% endif %}>
                                                    </td>
                                                </tr>
                                            {% endif %}
                                        {% endfor %}
                                    </table>
                                </td>
                                <td>
                                    {% if not mytask.0.task_by.profile.is_faculty %}
                                        <div class="col">
                                            <a target="_blank"
                                               href="
                                                       {{ host }}{{ media_dir }}{{ mytask.0.task_by.profile.hash_url.hex }}/{{ mytask.3 }}">
                                                <button onclick="" type="button"
                                                        class="small-btn btn action-btn shadow-none">
                                                    <i style="padding: 0" class="fas fa-eye"></i>
                                                </button>
                                            </a>
                                        </div>
                                        <div class="col">
                                            <label class="bs-switch">
                                                <input style="align-self: baseline;" onclick="add_print();" type="checkbox"
                                                       name="reprint{{ mytask.0.id }}" id="reprint{{ mytask.0.id }}">
                                                <span class="slider round"></span>
                                            </label>
                                        </div>
                                    {% endif %}
                                </td>
                            </tr>
                        {% endfor %}
                    </table>
                </div>

                <br>

                <button class="btn aqua-gradient">Update</button>

            </form>


        </center>
    </div>
    <script>
        const urlParams = new URLSearchParams(window.location.search);
        const query = urlParams.get('query');
        document.getElementById("query").value = query;
    </script>
{% endblock content %}

PrinterFac/Eprint_admin/templates/Eprint_admin/update.html
{% extends "ground/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="container-fluid col-md-4 content-below-nav">
        {% if messages %}
            {% for message in messages %}
                <center>
                    <ul style="list-style: none; padding: 0; margin: 0;">
                        <li class="alert alert-{{ message.tags }} alert-dismissible">
                            <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                            {{ message }}
                        </li>
                    </ul>
                </center>
            {% endfor %}
        {% endif %}
        <center><h2 class="py-3">Update Prices</h2></center>
        <div class="card p-3 ">
            <form method="post">
                {% csrf_token %}
                {{ update_form|crispy }}
                <center><button class="small-btn btn blue-gradient" type="submit">Update</button></center>
            </form>
        </div>
    </div>
{% endblock content %}